"use client";

import React, { useState } from "react";
import { Filter, ChevronDown } from "lucide-react";
import Sidebar from "../../website/Sidebar";
import DashboardHeader from "../../website/Header";

/* =======================
   CONSTANT DATA
======================= */

const FILTER_TABS = [
    "To be Picked",
    "In Picking",
    "Picked",
    "Picking",
    "Open",
    "All",
];

const TABLE_HEADERS = [
    "Picklist code",
    "Short Picked",
    "Sale Order Code",
    "Shipment Code",
    "Picked By",
    "Zone",
    "Generated By",
    "Status",
    "Created At",
    "Action",
];

const EMPTY_STATE_IMG = "https://images.unsplash.com/photo-1595411425732-e69c1abe2763?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhYnN0cmFjdCUyMGdlb21ldHJpYyUyMHBhdHRlcm58ZW58MXx8fHwxNzY5NTg5NDMyfDA&ixlib=rb-4.1.0&q=80&w=1080";

/* =======================
   REUSABLE COMPONENTS
======================= */

const FilterPill = ({ label, isActive, onClick }) => (
    <button
        onClick={onClick}
        className={`px-4 py-1.5 rounded-full text-[13px] font-medium border transition-all whitespace-nowrap ${
            isActive
                ? "bg-[#2b6cee] text-white border-[#2b6cee] shadow-sm"
                : "bg-white text-slate-400 border-slate-200 hover:border-blue-400 hover:text-blue-500"
        }`}
    >
        {label}
    </button>
);

const EmptyState = () => (
    <div className="flex flex-col items-center justify-center py-48 w-full">
        <div className="w-32 h-32 mb-4 opacity-40 grayscale flex items-center justify-center bg-slate-50 rounded-lg">
            <img src={EMPTY_STATE_IMG} alt="No records" className="w-20 h-20 object-contain" />
        </div>
        <p className="text-[14px] text-gray-500 font-medium tracking-tight">No records to show</p>
    </div>
);

/* =======================
   MAIN PAGE (Responsive for All Devices)
======================= */

export default function B2BPicklistsPage() {
    const [activeTab, setActiveTab] = useState("To be Picked");

    return (
        <div className="relative bg-white min-h-screen w-full font-sans antialiased">
            {/* Fixed Sidebar with responsive handling */}
            <div className="fixed top-0 left-0 h-screen w-auto z-30 flex">
                <Sidebar />
            </div>

            {/* Responsive Content Layout */}
            <div
                className={`
                    flex flex-col min-h-screen
                    transition-all
                    lg:pl-80 pl-16
                    md:pl-48
                    sm:pl-16
                    bg-white
                `}
            >
                {/* Global Header */}
                <DashboardHeader />

                {/* Sub-Header (Title & Tabs) */}
                <div className="sticky top-0 z-20 bg-white border-b border-gray-100">
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 px-4 md:px-6 py-4">
                        {/* Title & Tabs (scrollable) */}
                        <div className="flex items-center gap-4 md:gap-6 min-w-0">
                            <h1 className="text-[16px] md:text-xl font-bold text-slate-800 whitespace-nowrap hidden sm:block">
                                B2B Picklists
                            </h1>
                            <div className="flex items-center gap-2 overflow-x-auto no-scrollbar pb-1 sm:pb-0">
                                {FILTER_TABS.map((tab) => (
                                    <FilterPill
                                        key={tab}
                                        label={tab}
                                        isActive={activeTab === tab}
                                        onClick={() => setActiveTab(tab)}
                                    />
                                ))}
                            </div>
                        </div>
                        {/* Filter Button */}
                        <div className="flex items-center gap-2">
                            <button className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold border border-slate-300 text-slate-600 hover:bg-slate-50 transition-all shadow-sm">
                                <Filter size={16} />
                                <span className="hidden sm:inline">Filter</span>
                            </button>
                        </div>
                    </div>
                </div>

                {/* Table Section */}
                <main className="flex-1 p-2 sm:p-4 md:p-6 w-full max-w-[1600px] bg-white">
                    <div className="overflow-x-auto border border-gray-100 rounded-xl shadow-sm bg-white custom-scrollbar">
                        <div className="min-w-[1000px]">
                            {/* Table Header Row */}
                            <div className="flex items-center bg-[#eef4ff] border-b border-blue-100">
                                <div className="w-10 px-4 py-4 flex items-center justify-center">
                                    {/* Left margin indicator or checkbox space */}
                                    <div className="w-5 h-5 border-2 border-blue-100 rounded-full opacity-50" />
                                </div>
                                {TABLE_HEADERS.map((header, idx) => (
                                    <div
                                        key={idx}
                                        className="px-4 py-4 text-[13px] md:text-[14px] font-medium text-slate-600 whitespace-nowrap"
                                        style={{
                                            minWidth: "160px",
                                            flex: "1",
                                        }}
                                    >
                                        {header}
                                    </div>
                                ))}
                            </div>
                            {/* Empty State */}
                            <EmptyState />
                        </div>
                    </div>
                </main>
            </div>

            {/* Responsive Scrollbar & Sidebar Spacing Styles */}
            <style jsx global>{`
                .no-scrollbar::-webkit-scrollbar { display: none; }
                .no-scrollbar { -ms-overflow-style: none; scrollbar-width: none; }
                .custom-scrollbar::-webkit-scrollbar { height: 6px; background: transparent; }
                .custom-scrollbar::-webkit-scrollbar-thumb { background: #e6e7ee; border-radius: 10px; }
                @media (max-width: 1023px) {
                    .lg\\:pl-80 { padding-left: 4rem !important; }
                }
                @media (max-width: 767px) {
                    .md\\:pl-48 { padding-left: 4rem !important; }
                    .sm\\:pl-16 { padding-left: 4rem !important; }
                }
                @media (max-width: 640px) {
                    .sm\\:pl-16 { padding-left: 4rem !important; }
                }
            `}</style>
        </div>
    );
}