"use client";

import React, { useState } from "react";
import { Filter, Plus } from "lucide-react";
import Sidebar from "../../website/Sidebar";
import DashboardHeader from "../../website/Header";

/* =======================
   CONSTANT DATA
======================= */

const FILTER_TABS = [
    "To be Picked",
    "In Picking",
    "Picked",
    "Picking",
    "Open",
    "All",
];

const TABLE_HEADERS = [
    "Picklist code",
    "Picked By",
    "Zone",
    "Destination",
    "Type",
    "Generated By",
    "Status",
    "Created",
    "Operations",
];

const EMPTY_STATE_IMG =
    "https://images.unsplash.com/photo-1595411425732-e69c1abe2763?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080";

/* =======================
   REUSABLE COMPONENTS
======================= */

const FilterPill = ({ label, isActive, onClick }) => (
    <button
        onClick={onClick}
        className={`px-4 py-1.5 rounded-full text-[13px] font-medium border transition-all whitespace-nowrap ${isActive
            ? "bg-[#2b6cee] text-white border-[#2b6cee] shadow-sm"
            : "bg-white text-slate-400 border-slate-200 hover:border-blue-400 hover:text-blue-500"
            }`}
    >
        {label}
    </button>
);

const EmptyState = () => (
    <div className="flex flex-col items-center justify-center py-48 w-full">
        <div className="w-32 h-32 mb-4 opacity-40 grayscale flex items-center justify-center bg-slate-50 rounded-lg">
            <img src={EMPTY_STATE_IMG} alt="No data" className="w-20 h-20 object-contain" />
        </div>
        <p className="text-[14px] text-gray-500 font-medium">No records to show</p>
    </div>
);

/* =======================
   MAIN PAGE (Responsive for All Devices)
======================= */

export default function PicklistsPage() {
    const [activeTab, setActiveTab] = useState("To be Picked");

    return (
        <div
            className={`
                relative bg-white min-h-screen w-full font-sans antialiased
                flex
                /* Responsive sidebar handling */
            `}
        >
            {/* Fixed Sidebar */}
            <div className="fixed top-0 left-0 h-screen w-auto z-30 flex">
                <Sidebar />
            </div>
            {/* Responsive Content Layout */}
            <div
                className={`
                    flex flex-col min-h-screen flex-1
                    transition-all
                    lg:pl-80 pl-16
                    md:pl-48
                    sm:pl-16
                    bg-white
                    min-w-0
                `}
            >
                <DashboardHeader />
                {/* Sub-header */}
                <div
                    className="
                        flex flex-wrap items-center justify-between gap-4
                        px-4 md:px-6 py-4 border-b border-gray-100 bg-white
                        sticky top-0 z-20
                    "
                >
                    <div className="flex items-center gap-3 md:gap-6 overflow-x-auto no-scrollbar pb-1 sm:pb-0">
                        <h1 className="text-lg md:text-xl font-bold text-slate-800 whitespace-nowrap">Picklists</h1>
                        <div className="flex items-center gap-1 md:gap-2">
                            {FILTER_TABS.map((tab) => (
                                <FilterPill
                                    key={tab}
                                    label={tab}
                                    isActive={activeTab === tab}
                                    onClick={() => setActiveTab(tab)}
                                />
                            ))}
                        </div>
                    </div>

                    <div className="flex items-center gap-2 md:gap-3">
                        <button className="flex items-center gap-2 px-3 py-2 md:px-4 md:py-2 rounded-lg text-xs md:text-sm font-semibold border border-slate-300 text-slate-600 hover:bg-slate-50 transition-all shadow-sm">
                            <Filter size={16} />
                            <span className="hidden xs:inline">Filter</span>
                        </button>
                        <button className="flex items-center gap-2 bg-[#2b6cee] px-3 py-2 md:px-4 md:py-2 rounded-lg text-white hover:bg-blue-700 transition-all shadow-sm">
                            <Plus size={18} strokeWidth={3} />
                            <span className="hidden xs:inline text-[14px] font-semibold">Create Manual</span>
                        </button>
                    </div>
                </div>

                {/* 4. Data Table Section */}
                <div className="flex-1 overflow-x-auto overflow-y-auto">
                    <div className="min-w-max">
                        {/* Light Blue Table Header Row */}
                        <div className="flex items-center bg-[#eef4ff] border-b border-blue-100">
                            {/* Left Padding/Checkbox space placeholder */}
                            <div className="w-6 md:w-10" />
                            {TABLE_HEADERS.map((header, idx) => (
                                <div
                                    key={idx}
                                    className="px-2 md:px-4 py-3 md:py-4 text-[12px] md:text-[14px] font-medium text-slate-600 whitespace-nowrap"
                                    style={{
                                        minWidth: "120px",
                                        flex: "1"
                                    }}
                                >
                                    {header}
                                </div>
                            ))}
                        </div>
                        {/* 5. Table Body / Empty State */}
                        <EmptyState />
                    </div>
                </div>
            </div>

            <style jsx global>{`
                .no-scrollbar::-webkit-scrollbar { display: none; }
                .no-scrollbar { -ms-overflow-style: none; scrollbar-width: none; }
                @media (max-width: 1023px) {
                    /* When sidebar is collapsed on tablet/mobile, reserve only rail or collapsed width */
                    .lg\\:pl-80 { padding-left: 4rem !important; }
                }
                @media (max-width: 767px) {
                    .md\\:pl-48 { padding-left: 4rem !important; }
                    .sm\\:pl-16 { padding-left: 4rem !important; }
                }
                @media (max-width: 640px) {
                    .sm\\:pl-16 { padding-left: 4rem !important; }
                }
                @media (max-width: 768px) {
                    .min-w-max { min-width: 540px !important; }
                }
            `}</style>
        </div>
    );
}