"use client";
import React, { useState } from "react";
import { Search } from "lucide-react";
import Sidebar from "../../website/Sidebar";
import DashboardHeader from "../../website/Header";
import CreateReturnManifestModal from "./CreateManifestModal";

/* =======================
   CONSTANT DATA
======================= */
const FILTER_TABS = ["Open", "Pending", "All"];
const TABLE_COLUMNS = [
  "Manifest Code",
  "Shipping Provider",
  "No.of packages",
  "Closed",
  "Status",
  "Created",
  "Generated By"
];

export default function ReturnManifests() {
  const [activeTab, setActiveTab] = useState("Open");
  const [isModalOpen, setIsModalOpen] = useState(false);

  return (
    <div className="relative min-h-screen bg-white font-sans antialiased w-full">
      {/* Fixed Sidebar for large screens, collapses for small/tablet */}
      <div className="fixed top-0 left-0 h-screen w-auto z-30 flex">
        <Sidebar activePage="Returns" />
      </div>

      {/* Responsive MAIN CONTENT AREA: left padding for sidebar on large; collapses on mobile/tablet */}
      <div
        className={`
          flex flex-col min-h-screen
          transition-all
          lg:pl-80 pl-16
          md:pl-48
          sm:pl-16
          w-full
        `}
      >
        {/* Header */}
        <DashboardHeader />

        {/* Sub-header: Title, Filter Tabs, and Create Button - responsive stack for mobile */}
        <div className="flex flex-col md:flex-row md:items-center md:justify-between px-4 md:px-6 py-4 border-b border-gray-100 bg-white gap-3 md:gap-0">
          <div className="flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-6">
            <h1 className="text-base md:text-[16px] font-bold text-[#303e67] whitespace-nowrap">
              Return Manifests
            </h1>
            {/* Filter Tabs - Responsive */}
            <div className="flex gap-2 sm:gap-3 flex-wrap">
              {FILTER_TABS.map((tab) => (
                <button
                  key={tab}
                  onClick={() => setActiveTab(tab)}
                  className={`px-4 sm:px-5 py-1 sm:py-1.5 rounded-full text-xs font-semibold transition-all border ${
                    activeTab === tab
                      ? "bg-[#2b6cee] text-white border-[#2b6cee]"
                      : "text-gray-400 border-gray-300 hover:border-gray-400"
                  }`}
                >
                  {tab}
                </button>
              ))}
            </div>
          </div>
          <button
            onClick={() => setIsModalOpen(true)}
            className="bg-[#2b6cee] text-white px-6 py-2.5 md:px-5 md:py-2 rounded-lg text-sm font-semibold hover:bg-[#1e5bc7] transition-all shadow-sm"
          >
            Create Return Manifest
          </button>
        </div>

        {/* Table Area: Responsive (padding and table scroll) */}
        <main className="flex-1 p-4 sm:p-6 md:p-8 max-w-full xl:max-w-[1600px] w-full">
          <div className="overflow-x-auto">
            {/* Use min-w on table for horizontal scroll on mobile */}
            <table className="w-full text-left min-w-[800px] md:min-w-[1000px]">
              <thead>
                <tr className="bg-[#e9f0fe]">
                  {TABLE_COLUMNS.map((header, idx) => (
                    <th
                      key={idx}
                      className="px-6 py-4 text-[13px] font-semibold text-[#303d50] whitespace-nowrap"
                    >
                      {header}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {/* Empty State */}
                <tr>
                  <td colSpan={TABLE_COLUMNS.length} className="py-40">
                    <div className="flex flex-col items-center justify-center text-center">
                      <div className="relative w-32 h-32 mb-6">
                        <div className="absolute inset-0 bg-[#f8fafc] rounded-2xl border border-gray-100 flex items-center justify-center">
                          <div className="w-16 h-12 bg-[#ffd8b2] rounded shadow-sm relative flex items-center justify-center">
                            <Search className="text-[#2b6cee]" size={28} />
                          </div>
                        </div>
                      </div>
                      <p className="text-[14px] text-gray-500 font-medium tracking-tight">
                        No records to show
                      </p>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </main>
      </div>

      {/* RENDER MODAL */}
      <CreateReturnManifestModal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
      />

      {/* Responsive styling helper */}
      <style>{`
        @media (max-width: 1023px) {
          .lg\\:pl-80 { padding-left: 4rem !important; }
        }
        @media (max-width: 767px) {
          .md\\:pl-48 { padding-left: 4rem !important; }
          .sm\\:pl-16 { padding-left: 4rem !important; }
        }
        @media (max-width: 640px) {
          .sm\\:pl-16 { padding-left: 4rem !important; }
        }
      `}</style>
    </div>
  );
}