
import React, { useState } from "react";
import { Search } from "lucide-react";
import Sidebar from "../../website/Sidebar";
import DashboardHeader from "../../website/Header";
import CreatePutawayModal from "./CreatePutawayModal";

/* === TABLE HEADERS === */
const TABLE_COLUMNS = [
    "Putaway Number",
    "Type",
    "Generated by",
    "Sku Code",
    "Qty",
    "Status",
    "Putaway Category",
    "Created At",
    "Updated At",
    "Pending Qty At",
];

export default function InboundPutaway() {
    const [activeTab, setActiveTab] = useState("Pending");
    const [isModalOpen, setIsModalOpen] = useState(false);

    return (
        <div className="relative bg-white min-h-screen w-full font-sans antialiased">
            {/* 1. Sidebar */}
            <div className="fixed top-0 left-0 h-screen w-auto z-30 flex">
                <Sidebar activePage="Putaway" />
            </div>

            {/* Responsive Content Layout */}
            <div
                className={`
                    flex flex-col min-h-screen
                    transition-all
                    lg:pl-80 pl-16
                    md:pl-48
                    sm:pl-16
                    bg-white
                `}
            >
                {/* 2. Global Header */}
                <DashboardHeader />

                {/* 3. Breadcrumb Header or Sub-header (Title, Tabs, and Create Button) */}
                <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 sm:gap-0 px-3 sm:px-4 md:px-6 py-3 sm:py-4 border-b border-gray-100 bg-white">
                    <div className="flex flex-wrap items-center gap-3 sm:gap-6">
                        <h1 className="text-base sm:text-[16px] font-bold text-[#303e67]">Putaway</h1>
                        {/* Status Tabs */}
                        <div className="flex gap-2 sm:gap-3">
                            <button
                                onClick={() => setActiveTab("Pending")}
                                className={`px-4 sm:px-5 py-1.5 rounded-full text-xs font-semibold transition-all border ${
                                    activeTab === "Pending"
                                        ? "bg-[#2b6cee] text-white border-[#2b6cee]"
                                        : "text-gray-400 border-gray-300 hover:border-gray-400"
                                }`}
                            >
                                Pending
                            </button>
                            <button
                                onClick={() => setActiveTab("All")}
                                className={`px-4 sm:px-5 py-1.5 rounded-full text-xs font-semibold transition-all border ${
                                    activeTab === "All"
                                        ? "bg-[#2b6cee] text-white border-[#2b6cee]"
                                        : "text-gray-400 border-gray-300 hover:border-gray-400"
                                }`}
                            >
                                All
                            </button>
                        </div>
                    </div>
                    {/* Create Button */}
                    <button
                        onClick={() => setIsModalOpen(true)}
                        className="bg-[#2b6cee] text-white px-4 sm:px-5 py-2 rounded-lg text-sm font-semibold hover:bg-[#1e5bc7] transition-all shadow-sm"
                    >
                        Create Putaway
                    </button>
                </div>

                {/* 4. Table Area (responsive spacing and width) */}
                <main className="flex-1 p-2 sm:p-4 md:p-8 max-w-full md:max-w-[1600px]">
                    <div className="overflow-x-auto">
                        <table className="w-full text-left min-w-[700px] md:min-w-[1400px]">
                            <thead>
                                <tr className="bg-[#e9f0fe]">
                                    {TABLE_COLUMNS.map((header, idx) => (
                                        <th
                                            key={idx}
                                            className="px-3 sm:px-4 md:px-6 py-3 sm:py-4 text-[12px] sm:text-[13px] font-semibold text-[#303d50] whitespace-nowrap"
                                        >
                                            {header}
                                        </th>
                                    ))}
                                </tr>
                            </thead>

                            <tbody>
                                {/* Empty State Body */}
                                <tr>
                                    <td colSpan={TABLE_COLUMNS.length} className="py-24 sm:py-32 md:py-40">
                                        <div className="flex flex-col items-center justify-center text-center">
                                            <div className="relative w-24 h-24 sm:w-28 sm:h-28 md:w-32 md:h-32 mb-6">
                                                <div className="absolute inset-0 bg-[#f8fafc] rounded-2xl border border-gray-100 flex items-center justify-center">
                                                    <div className="w-12 h-10 sm:w-14 sm:h-12 md:w-16 md:h-12 bg-[#ffd8b2] rounded shadow-sm relative flex items-center justify-center">
                                                        <Search className="text-[#2b6cee]" size={24} />
                                                    </div>
                                                </div>
                                            </div>
                                            <p className="text-[13px] sm:text-[14px] text-gray-500 font-medium tracking-tight">
                                                No records to show
                                            </p>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </main>
            </div>

            {/* 5. Create Putaway Modal */}
            <CreatePutawayModal
                isOpen={isModalOpen}
                onClose={() => setIsModalOpen(false)}
            />

            {/* Responsive custom scrollbar and sidebar paddings for mobile/tablet */}
            <style>{`
                @media (max-width: 1023px) {
                    .lg\\:pl-80 { padding-left: 4rem !important; }
                }
                @media (max-width: 767px) {
                    .md\\:pl-48 { padding-left: 4rem !important; }
                    .sm\\:pl-16 { padding-left: 4rem !important; }
                }
                @media (max-width: 640px) {
                    .sm\\:pl-16 { padding-left: 4rem !important; }
                }
                /* Responsive scroll if content exceeds screen */
                .custom-scrollbar::-webkit-scrollbar { width: 6px; background: transparent; }
                .custom-scrollbar::-webkit-scrollbar-thumb { background: #e6e7ee; border-radius: 10px; }
                .custom-scrollbar { scrollbar-width: thin; scrollbar-color: #e6e7ee transparent; }
            `}</style>
        </div>
    );
}