"use client";

import React, { useState } from "react";
import Sidebar from "../../website/Sidebar";
import DashboardHeader from "../../website/Header";

/* =======================
   CONSTANT DATA
======================= */

const TABS = [
    { label: "Unfulfilled", value: "unfulfilled" },
    { label: "Pending", value: "pending" },
    { label: "All", value: "all" },
];

const COLUMNS = [
    "Warehouse",
    "Invoice",
    "Generated By",
    "Created At",
    "Created On Channel At",
    "Shipping Package",
    "Channel",
    "Sale Order Code",
    "Customer name",
    "Quantity",
    "Amount Details",
    "Invoice Type",
    "Gst E-invoice Status",
];

const EMPTY_STATE_IMAGE = "https://images.unsplash.com/photo-1595411425732-e69c1abe2763?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080";

/* =======================
   REUSABLE COMPONENTS
======================= */

const TabButton = ({ label, isActive, onClick }) => (
    <button
        onClick={onClick}
        className={`px-4 py-1 rounded-full text-[12px] font-semibold transition-all border shrink-0 ${isActive
                ? "bg-[#2b6cee] text-white border-[#2b6cee]"
                : "bg-white text-[#94a3b8] border-[#94a3b8] hover:bg-slate-50"
            }`}
    >
        {label}
    </button>
);

const EmptyState = () => (
    <div className="flex flex-col items-center justify-center py-32 w-full">
        <div className="w-32 h-32 mb-4 opacity-60 grayscale">
            <img
                src={EMPTY_STATE_IMAGE}
                alt="No data"
                className="w-full h-full object-contain"
            />
        </div>
        <p className="text-[14px] text-gray-900 font-medium">No records to show</p>
    </div>
);

/* =======================
   MAIN PAGE COMPONENT
======================= */

export default function InvoiceReportPage() {
    const [activeTab, setActiveTab] = useState("unfulfilled");

    return (
        <div className="flex min-h-screen bg-white font-sans antialiased">
            {/* 1. Sidebar Component */}
            <Sidebar />

            <div className="flex-1 flex flex-col min-w-0">
                {/* 2. Header Component */}
                <DashboardHeader />

                {/* 3. Filter Bar */}
                <div className="flex items-center gap-8 px-6 py-3 border-b border-gray-200">
                    <h1 className="text-[16px] font-bold text-[#303e67]">Invoice</h1>
                    <div className="flex items-center gap-3">
                        {TABS.map((tab) => (
                            <TabButton
                                key={tab.value}
                                label={tab.label}
                                isActive={activeTab === tab.value}
                                onClick={() => setActiveTab(tab.value)}
                            />
                        ))}
                    </div>
                </div>

                {/* 4. Data Table Container */}
                <div className="flex-1 overflow-x-auto overflow-y-auto">
                    <div className="min-w-max">
                        {/* Table Header Row */}
                        <div className="flex items-center bg-[#2b6cee26] border-b border-blue-100">
                            {COLUMNS.map((col, index) => (
                                <div
                                    key={index}
                                    className="px-4 py-4 text-[14px] font-semibold text-[#303d50] whitespace-nowrap"
                                    style={{
                                        minWidth: col.length > 15 ? "180px" : "140px"
                                    }}
                                >
                                    {col}
                                </div>
                            ))}
                        </div>

                        {/* Table Content (Empty State) */}
                        <EmptyState />
                    </div>
                </div>
            </div>
        </div>
    );
}